"""empty message

Revision ID: b46c0348f3e9
Revises: 3ac891d4b6c4
Create Date: 2016-11-09 15:43:16.255433

"""

# revision identifiers, used by Alembic.
revision = 'b46c0348f3e9'
down_revision = '3ac891d4b6c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('important', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
